[allowlist]
description = "False positives for various secrets"
rules = ["hashicorp-tf-password", "private-key"]
paths = [
  "app/src/main/java/com/example/presencedetector/security/model/DetectionSettings.kt",
  "app/google-services.json",
]
